//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace netcfg.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("netcfg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cdebyte {
            get {
                object obj = ResourceManager.GetObject("cdebyte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cdebyte1 {
            get {
                object obj = ResourceManager.GetObject("cdebyte1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 *E810-TTL-01*
        ///*E810 (232)*
        ///*E810(485)*
        ///*E810-DTU (433N30)*
        ///{
        ///	class:1#
        ///    configMode:3,0#
        ///    configBaudRate:9600#
        ///    version:1,08001E0400#
        ///    MTU:186#
        ///    Factory Settings:C0 00 00 18 50 44#
        ///	:21 - 30 dBm/410 - 441Mhz/窄带传输 ,21 - 30 dBm/410 - 441Mhz/Narrow-band transmission#
        ///    T@0: # T@1: #
        ///	L@0:工作模式,Mode# C@0:一般模式/唤醒模式/省电模式/休眠模式,General Mode/Wakeup Mode/Power Saving Mode/Sleep Mode#
        ///	L@1:模块地址,Sddress#   T@2: #
        ///	L@2:奇偶校验,Parity# C@1:8N1/8O1/8E1,8N1/8O1/8E1#
        ///	L@3:波特率,BaudRate# C@2:1200/2 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 配置 {
            get {
                return ResourceManager.GetString("配置", resourceCulture);
            }
        }
    }
}
